networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.5.0/24
          ip_range: 172.28.5.0/24
          gateway: 172.28.5.1

volumes:
  mysql-olx-tracker:
  nginx_log:
  nginx_etc_letsencrypt:

services:
  db:
    image: mysql/mysql-server:8.0
    # ports:
      # - 3306:3306/tcp
    expose:
      - 3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'helig-root'
      MYSQL_ROOT_HOST: '0.0.0.0'
      MYSQL_DATABASE: 'olx-tracker-db'
      MYSQL_USER: 'olx-tracker-user'
      MYSQL_PASSWORD: 'olx-tracker-pass-123'
    volumes:
        - mysql-olx-tracker:/var/lib/mysql

  app:
    image: helig13/olx-tracker:app
    build:
      dockerfile: Dockerfile
    # ports:
    #   - 8000:8000/tcp
    expose:
      - 8000
    restart: unless-stopped
    depends_on:
      - db
    environment:
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      FILESYSTEM_DISK: local
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:UiTGp9Nv4A0YvFiqwJ/Llrvu5xIAtpgg0Z8n/rkZFv8=
      APP_DEBUG: true
      APP_URL: http://localhost
      APP_PORT: 55
      LOG_CHANNEL: stack
      LOG_DEPRECATIONS_CHANNEL: null
      LOG_LEVEL: debug
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: olx-tracker-db
      DB_USERNAME: olx-tracker-user
      DB_PASSWORD: olx-tracker-pass-123
      MAIL_MAILER: smtp
      MAIL_HOST: sandbox.smtp.mailtrap.io
      MAIL_PORT: 2525
      MAIL_USERNAME: 85243cc9473e1c
      MAIL_PASSWORD: 30607772697912
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: "hello@example.com"
      MAIL_FROM_NAME: helig-app

  nginx:
    build:
      dockerfile: Dockerfile
      context: nginx
      args:
        - NGINX_VERSION=1.19.1
    restart: unless-stopped
    image: helig13/olx-tracker:nginx
    depends_on:
      - app
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - nginx_log:/var/log/nginx
      - nginx_etc_letsencrypt:/etc/letsencrypt
